# stgen/comparator.py
"""
@file comparator.py
@brief Protocol Comparison Framework
@details Runs multiple protocols on the same workload (scenario) sequentially and generates 
         comparative reports. This module is essential for the "Case Study" aspect of STGen,
         allowing direct head-to-head comparison of metrics like latency and packet loss.
"""

import json
import time
import logging
from pathlib import Path
from typing import List, Dict, Any
import subprocess
import sys

# @brief Logger for the comparator module
_LOG = logging.getLogger("stgen.compare")


class ProtocolComparator:
    """
    @brief Compare multiple protocols on identical workloads.
    
    @details Orchestrates the execution of the main STGen process for different protocols
             using a shared scenario configuration. It collects the resulting metrics
             and generates a textual report highlighting the differences.
    """

    def __init__(self, scenario_file: str, protocols: List[str]):
        """
        @brief Initialize comparator.
        
        @param scenario_file Path to the scenario configuration JSON file.
        @param protocols List of protocol names (strings) to compare (e.g., ["mqtt", "coap"]).
        """
        self.scenario = json.loads(Path(scenario_file).read_text())
        self.protocols = protocols
        self.results: Dict[str, Dict] = {}

        _LOG.info("Comparing protocols: %s on scenario: %s",
                  protocols, self.scenario.get("name", "unknown"))

    def run_comparison(self) -> Dict[str, Any]:
        """
        @brief Run all protocols on the same scenario.
        
        @details Iterates through the list of protocols. For each protocol:
                 1. Creates a temporary configuration file based on the scenario but with the specific protocol.
                 2. Launches a subprocess running `stgen.main` with this config.
                 3. Locates the results generated by that run.
                 4. Parsed the summary.json and stores it in memory.
        
        @return Dict[str, Any] Dictionary mapping protocol names to their result summary dictionaries.
        """
        for protocol in self.protocols:
            _LOG.info("=" * 60)
            _LOG.info("Testing protocol: %s", protocol)
            _LOG.info("=" * 60)

            # Create temporary config
            cfg = self.scenario.copy()
            cfg["protocol"] = protocol

            temp_config = Path(f"temp_{protocol}_config.json")
            temp_config.write_text(json.dumps(cfg, indent=2))

            # Run test
            try:
                subprocess.run(
                    [sys.executable, "-m", "stgen.main", str(temp_config)],
                    check=True
                )

                # Load results
                result_dirs = sorted(Path("results").glob(f"{protocol}_*"))
                if result_dirs:
                    latest = result_dirs[-1]
                    summary = json.loads((latest / "summary.json").read_text())
                    self.results[protocol] = summary
                    _LOG.info(" %s test completed", protocol)
                else:
                    _LOG.error(" No results found for %s", protocol)

            except subprocess.CalledProcessError as e:
                _LOG.error(" %s test failed: %s", protocol, e)
            finally:
                temp_config.unlink(missing_ok=True)

            time.sleep(2)  # Cool-down between tests

        return self.results

    def generate_report(self, output_file: str = "comparison_report.txt") -> None:
        """
        @brief Generate comparison report.
        
        @details Creates a text-based table comparing key metrics (sent, recv, loss, latency)
                 against a baseline (the first protocol in the list). It calculates percentage
                 deltas to show improvements or regressions.
        
        @param output_file File path where the report text will be saved.
        @return None
        """
        if not self.results:
            _LOG.error("No results to compare")
            return

        report = []
        report.append("=" * 80)
        report.append(f"PROTOCOL COMPARISON REPORT")
        report.append(f"Scenario: {self.scenario.get('name', 'Unknown')}")
        report.append(f"Date: {time.strftime('%Y-%m-%d %H:%M:%S')}")
        report.append("=" * 80)
        report.append("")

        # Extract metrics
        metrics = ["sent", "recv", "loss", "lat_avg_ms",
                   "lat_p50_ms", "lat_p95_ms", "lat_p99_ms"]

        # Find baseline (first protocol)
        baseline_name = self.protocols[0]
        baseline = self.results.get(baseline_name, {})

        # Build header line
        header = f"{'Metric':<25} {baseline_name:<15}"
        for proto in self.protocols[1:]:
            header += f" {proto:<15} Δ vs {baseline_name:<10}"
        report.append(header)
        report.append("-" * 80)

        for metric in metrics:
            if metric not in baseline:
                continue

            line = f"{metric:<25} "
            baseline_val = baseline[metric]

            # Format baseline value
            if "loss" in metric:
                line += f"{baseline_val*100:>6.2f}%     "
            elif "lat" in metric or "ms" in metric:
                line += f"{baseline_val:>6.2f}ms    "
            else:
                line += f"{baseline_val:>6.0f}        "

            # Compare with other protocols
            for proto in self.protocols[1:]:
                proto_val = self.results.get(proto, {}).get(metric, 0)

                # Calculate delta
                if baseline_val > 0:
                    delta_pct = ((proto_val - baseline_val) /
                                 baseline_val) * 100
                else:
                    delta_pct = 0

                # Format value
                if "loss" in metric:
                    line += f"{proto_val*100:>6.2f}%  "
                elif "lat" in metric or "ms" in metric:
                    line += f"{proto_val:>6.2f}ms "
                else:
                    line += f"{proto_val:>6.0f}     "

                # Format delta with direction
                if "lat" in metric:
                    # Lower latency is better
                    symbol = "↓" if delta_pct < 0 else "↑"
                elif "loss" in metric:
                    # Lower loss is better
                    symbol = "↓" if delta_pct < 0 else "↑"
                else:
                    # Higher throughput is better
                    symbol = "↑" if delta_pct > 0 else "↓"

                line += f"{delta_pct:>+6.1f}% {symbol}  "

            report.append(line)

        report.append("")
        report.append("=" * 80)
        report.append("SUMMARY")
        report.append("=" * 80)

        # Determine winner
        winner = self._determine_winner()
        report.append(f"\n Best Overall: {winner['protocol']}")
        report.append(f"   Reason: {winner['reason']}")

        # Save report
        report_text = "\n".join(report)
        Path(output_file).write_text(report_text)
        _LOG.info("Report saved to: %s", output_file)
        print(report_text)

    def _determine_winner(self) -> Dict[str, str]:
        """
        @brief Determine which protocol performed best.
        
        @details Uses a simple scoring heuristic:
                 - Higher score is better.
                 - Penalizes high latency (P95).
                 - Heavily penalizes packet loss.
                 - Rewards successful packet delivery count.
        
        @return Dict[str, str] Dictionary containing 'protocol' name and the 'reason' string.
        """
        # Simple scoring: lower latency + lower loss = better
        scores = {}

        for proto, results in self.results.items():
            score = 0

            # Penalize high latency
            if "lat_p95_ms" in results:
                score -= results["lat_p95_ms"]

            # Penalize packet loss
            if "loss" in results:
                score -= results["loss"] * 1000

            # Reward throughput (messages delivered)
            if "recv" in results:
                score += results["recv"]

            scores[proto] = score

        if scores:
            winner_proto = max(scores, key=scores.get)
            return {
                "protocol": winner_proto,
                "reason": f"Lowest latency ({self.results[winner_proto].get('lat_p95_ms', 0):.2f}ms) and loss ({self.results[winner_proto].get('loss', 0)*100:.1f}%)"
            }

        return {"protocol": "Unknown", "reason": "No results"}


def main():
    """
    @brief CLI for comparison tool.
    
    @details Parses arguments for scenario, protocols, and output file, then 
             instantiates ProtocolComparator to run the comparison.
             
    @return None
    """
    import argparse

    parser = argparse.ArgumentParser(description="Compare IoT protocols")
    parser.add_argument("--scenario", required=True,
                        help="Scenario config file")
    parser.add_argument("--protocols", required=True,
                        help="Comma-separated protocol names")
    parser.add_argument(
        "--output", default="comparison_report.txt", help="Output file")

    args = parser.parse_args()

    protocols = [p.strip() for p in args.protocols.split(",")]

    comparator = ProtocolComparator(args.scenario, protocols)
    comparator.run_comparison()
    comparator.generate_report(args.output)


if __name__ == "__main__":
    main()
