# stgen/energy_model.py
"""
@file energy_model.py
@brief Energy consumption modeling for battery-powered IoT devices.
@details This module provides the `EnergyModel` class, which estimates the battery lifetime
         of an IoT device based on physical power characteristics (Tx/Rx/Sleep) and 
         traffic patterns observed during simulation.
"""

import logging
from typing import Dict, Any

# @brief Logger for the energy model module
_LOG = logging.getLogger("energy_model")


class EnergyModel:
    """
    @brief Estimate energy consumption based on traffic patterns.
    
    @details This class models a generic battery-powered IoT device. It uses defined 
             power profiles for different states (Transmission, Reception, Idle, Sleep) 
             and calculates the total energy drain over a 24-hour period to estimate 
             total battery life in days.
             
    @note The physical device assumptions (POWER_PROFILES, TIMINGS) are currently set 
          to example values (likely LoRaWAN-ish). These MUST be tuned to match the 
          specific hardware being simulated (e.g., ESP32, nRF52).
    """

    # PHYSICAL DEVICE ASSUMPTIONS (CRITICAL: TUNE THESE)
    # @brief Power draw in milliwatts (mW) for each state.
    POWER_PROFILES = {
        "tx": 50,
        "rx": 30, 
        "idle": 0.5,
        "sleep": 0.01
    }

    # @brief Time-on-air and processing time in seconds (s).
    TIME_PER_TX_S = 0.150 
    TIME_PER_RX_S = 0.100   
    TIME_IDLE_PER_EVENT_S = 0.5

    # @brief Battery capacity in milliampere-hours (mAh).
    BATTERY_MAH = 2000

    # @brief Operating voltage in Volts (V).
    VOLTAGE = 3.3
    # --------------------------------------------------------------------

    def estimate_battery_life(self,
                              traffic_pattern: Dict[str, Any],
                              sim_results: Dict[str, Any],
                              duration_s: int) -> float:
        """
        @brief Estimate battery lifetime in days based on traffic and simulation results.
        
        @details Calculates the total energy consumed per day by determining how many 
                 seconds the device spends in TX, RX, IDLE, and SLEEP states.
                 
                 Logic Flow:
                 1. Determine total events per day.
                    - Priority: Use actual `sent` packet count from `sim_results`.
                    - Fallback: Use theoretical `rate_hz` from `traffic_pattern`.
                 2. Calculate total time spent in active states (TX/RX/IDLE).
                 3. Remainder of the day is assumed to be SLEEP.
                 4. Convert time/power to Energy (mWh).
                 5. Divide Total Battery Capacity by Daily Consumption.
        
        @param traffic_pattern The "traffic_pattern" dict from the scenario JSON (fallback data).
        @param sim_results The 'summary.json' dict generated by the orchestrator (actual data).
        @param duration_s The total duration of the test in seconds.
        
        @return float Estimated battery lifetime in days. Returns infinity if no energy is consumed.
        """

        total_events_per_day = 0

        # 1. Prioritize ACTUAL sent packets from the simulation
        packets_sent_in_test = sim_results.get("sent", 0)

        if packets_sent_in_test > 0 and duration_s > 0:
            # Calculate events/day based on real test performance
            rate_hz = packets_sent_in_test / duration_s
            total_events_per_day = rate_hz * 3600 * 24
            _LOG.info(
                f"Model: Calculating based on *actual* sim results ({packets_sent_in_test} packets in {duration_s}s)")

        # 2. Fallback to traffic_pattern if 'sent' is 0
        elif traffic_pattern:
            _LOG.warning(
                "No packets sent in sim, falling back to 'traffic_pattern' estimate.")
            for sensor, config in traffic_pattern.items():
                rate_hz = config.get("rate_hz", 0)
                events_per_day = rate_hz * 3600 * 24
                total_events_per_day += events_per_day
        # --- END MODIFIED LOGIC ---

        if total_events_per_day == 0:
            _LOG.warning(
                "No traffic events found, cannot estimate battery life.")
            return float('inf')

        _LOG.info(
            f"Model: Calculating for {total_events_per_day:.2f} events/day.")

        # --- (Rest of the function is the same) ---

        # 2. Calculate total time (in seconds) spent PER DAY in each state
        total_time_tx_s = total_events_per_day * self.TIME_PER_TX_S
        total_time_rx_s = total_events_per_day * self.TIME_PER_RX_S
        total_time_idle_s = total_events_per_day * self.TIME_IDLE_PER_EVENT_S

        total_awake_time_s = total_time_tx_s + total_time_rx_s + total_time_idle_s
        total_seconds_in_day = 24 * 3600
        total_sleep_time_s = total_seconds_in_day - total_awake_time_s

        if total_sleep_time_s < 0:
            total_sleep_time_s = 0
            total_time_idle_s = total_seconds_in_day - total_time_tx_s - total_time_rx_s

        # 3. Convert time (sec) to energy (mWh)
        energy_tx_mwh = self.POWER_PROFILES["tx"] * (total_time_tx_s / 3600)
        energy_rx_mwh = self.POWER_PROFILES["rx"] * (total_time_rx_s / 3600)
        energy_idle_mwh = self.POWER_PROFILES["idle"] * \
            (total_time_idle_s / 3600)
        energy_sleep_mwh = self.POWER_PROFILES["sleep"] * \
            (total_sleep_time_s / 3600)

        total_energy_per_day_mwh = energy_tx_mwh + \
            energy_rx_mwh + energy_idle_mwh + energy_sleep_mwh

        if total_energy_per_day_mwh == 0:
            return float('inf')

        _LOG.info(
            f"Model: Daily energy use: {total_energy_per_day_mwh:.4f} mWh")

        # 4. Calculate total battery capacity (mWh)
        total_battery_capacity_mwh = self.BATTERY_MAH * self.VOLTAGE

        # 5. Calculate final lifetime
        estimated_lifetime_days = total_battery_capacity_mwh / total_energy_per_day_mwh

        return estimated_lifetime_days
